name: Test

on:
  pull_request:
    branches: [ master ]  # master 브랜치에 push 시 실행

jobs:
  test:
    runs-on: ubuntu-latest  # 최신 LTS 버전 사용
    permissions:
      checks: write # 체크 실행 결과 표시 권한
      contents: read # 저장소 read 권한
      pull-requests: write  # PR에 코멘트 작성 허용
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle  # Gradle 캐싱 활성화

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2 # JUnit, NUnit, xUnit 등의 테스트 결과를 자동으로 PR에 표시하는 GitHub Action
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml' # gradle의 테스트 결과 파일
